export const DUMMY_TASKS = [
  {
    id: 't1',
    title: 'Revisar propuesta de diseño',
    dueDate: '2025-07-27T10:15:00Z',
    summary:
      'Validar las secciones visuales antes de la revisión final del cliente.',
    complete: false,
    userId: 'u1',
  },
  {
    id: 't2',
    title: 'Actualizar documentación técnica',
    dueDate: '2025-07-26T14:45:00Z',
    summary: 'Agregar nuevos endpoints REST al documento compartido.',
    complete: true,
    userId: 'u2',
  },
  {
    id: 't3',
    title: 'Configurar servidor de staging',
    dueDate: '2025-07-28T09:00:00Z',
    summary: 'Preparar el entorno de pruebas para el release semanal.',
    complete: false,
    userId: 'u3',
  },
  {
    id: 't4',
    title: 'Crear mockups del dashboard',
    dueDate: '2025-07-25T16:30:00Z',
    summary: 'Generar prototipos responsivos con base en el nuevo layout.',
    complete: true,
    userId: 'u4',
  },
  {
    id: 't5',
    title: 'Escribir pruebas unitarias',
    dueDate: '2025-07-24T11:20:00Z',
    summary: 'Cubrir los nuevos reducers y efectos del store.',
    complete: false,
    userId: 'u5',
  },
  {
    id: 't6',
    title: 'Coordinar reunión de equipo',
    dueDate: '2025-07-29T08:00:00Z',
    summary: 'Definir agenda para el cierre de sprint y retrospectiva.',
    complete: false,
    userId: 'u6',
  },
  {
    id: 't7',
    title: 'Optimizar queries en la base de datos',
    dueDate: '2025-07-23T13:15:00Z',
    summary: 'Reducir latencia en los endpoints críticos.',
    complete: true,
    userId: 'u3',
  },
  {
    id: 't8',
    title: 'Diseñar estructura de componente modular',
    dueDate: '2025-07-28T18:00:00Z',
    summary: 'Separar lógica visual y funcional del panel de métricas.',
    complete: false,
    userId: 'u2',
  },
  {
    id: 't9',
    title: 'Integrar señales reactivas en el feature de notificaciones',
    dueDate: '2025-07-27T20:10:00Z',
    summary: 'Actualizar lógica para usar Signals en lugar de Subjects.',
    complete: true,
    userId: 'u5',
  },
  {
    id: 't10',
    title: 'Rediseñar mixins para utilidades CSS',
    dueDate: '2025-07-22T17:00:00Z',
    summary: 'Mejorar la reusabilidad de los mixins de espaciado y bordes.',
    complete: true,
    userId: 'u1',
  },
];
